# Site settings
theme: jekyll-theme-minimal
title: brainsesh
description: A space dedicated to thinking, learning, and intellectual curiosity.
repository: brainsesh/brainsesh.github.io
url: https://brainsesh.github.io
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
show_downloads: false

# Authors/Contributors
authors:
  - name: LB
    photo: /images/logo2.jpg
    bio: Founder and Contributor for brainsesh
  - name: RB
    photo: /images/logo2.jpg
    bio: Founder and Contributor for brainsesh

# Left sidebar settings
sidebar:
  show_github_stats: true
  github_stats:
    stars: true
    forks: true
    issues: true
  
# Google Analytics
google_analytics: # your Google Analytics tracking ID here

# Social links
social:
  github: brainsesh/brainsesh.github.io
  # linkedin: # your LinkedIn username

# Display settings
logo: /images/logo2.jpg
show_header: true
show_footer: true