# Site settings
theme: jekyll-theme-minimal
title: brainsesh
description: A space dedicated to growth, reflection, and inspiration.
# logo: /images/logo2.jpg
repository: brainsesh/brainsesh.github.io
url: https://brainsesh.github.io
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
show_downloads: false

# Google Analytics
# google_analytics: # your Google Analytics tracking ID here