# Minima theme configuration with custom header: logo on left, contact email on right

title: brainsesh
description: A space dedicated to thinking, learning, and intellectual work.
theme: minima

# Site logo (will appear on the left in the header)
logo: /images/logo.jpg

# Author/contact info
author:
  name: brainsesh
  email: brainsesh@gmail.com

# Minima theme settings
minima:
  social_links:
    - title: Email
      url: mailto:brainsesh@gmail.com
      icon: fas fa-envelope
  # Custom header links (optional)
  header_links:
    - title: Sesh
      url: /#sesh
    - title: Titbits
      url: /#titbits
    - title: Contact
      url: /#contact

# Custom CSS for layout tweaks (create /assets/css/custom.css)
sass:
  style: compressed

# Include custom CSS
include:
  - assets/css/custom.css

# Remove GitHub/Jekyll default footer links
show_downloads: false
github:
  is_project_page: false
improve_this_page: false
show_edit_on_github: false
edit_on_github: false